version: '3.7'
services:
  opencart:
    build: ./config/docker/opencart
    container_name: opencart
    environment:
      - OPENCART_VERSION
      - OPENCART_PORT
      - DB_PORT
      - USERNAME
      - PASSWORD
    volumes:
      - ./.opencart:/var/www/html
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - '${OPENCART_PORT}:80'
    volumes:
      - ./.opencart:/var/www/html
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - opencart
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=opencart
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
        PMA_HOST: mariadb
    ports:
      - '${PMA_PORT}:80'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
