version: '3.7'
services:
  opencart:
    build: ./config/docker/opencart
    volumes:
      - ./.opencart:/var/www/html
  nginx:
    image: nginx:1.21-alpine
    ports:
      - '${PORT}:80'
    volumes:
      - ./.opencart:/var/www/html
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - opencart
  mariadb:
    image: mariadb:10.5
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=opencart
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    environment:
        PMA_HOST: mariadb
    ports:
      - '${PMA_PORT}:80'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
